const novaService = require('./novaService');
const Task = require('../models/Task');

/**
 * Agent Workflow Engine
 * Responsible for reasoning, planning, and executing multi-step AI workflows.
 */
class WorkflowService {
    /**
     * Main function to execute the agentic workflow
     * @param {string} command - The user's natural language command
     * @param {string} documentText - Optional text from an uploaded document
     */
    async executeAgentWorkflow(command, documentText = "") {
        console.log(`\n🤖 Agent Input Received: "${command}"`);

        try {
            // Step 1 & 2: Intent Detection & Analysis
            // We ask Nova to analyze the command and return structured intents
            const intentPrompt = `
        Analyze the following user command and identify all high-level intents.
        Command: "${command}"
        Possible intents: ["summarize_document", "generate_tasks", "plan_schedule", "draft_email", "general_chat"]
        
        Return ONLY a JSON object in this format:
        { "intents": ["intent1", "intent2"] }
      `;

            const analysisResponse = await novaService.invokeNova(intentPrompt, "You are an Intent Detection Agent.");
            let intents = ["general_chat"];

            try {
                const parsed = JSON.parse(analysisResponse.match(/\{.*\}/s)?.[0] || analysisResponse);
                intents = parsed.intents || intents;
            } catch (e) {
                console.warn("⚠️ Failed to parse intent JSON, falling back to keyword detection.");
                if (command.toLowerCase().includes("summarize")) intents.push("summarize_document");
                if (command.toLowerCase().includes("task") || command.toLowerCase().includes("todo")) intents.push("generate_tasks");
            }

            console.log("🎯 Agent Detected Intents:", intents);

            // Step 3: Task Planning
            // Create a step-by-step execution plan based on detected intents
            const executionPlan = intents.map((intent, index) => ({
                step: index + 1,
                action: intent
            })).filter(step => step.action !== "general_chat" || intents.length === 1);

            console.log("📝 Execution Plan:", executionPlan);

            // Step 4: Execute Steps sequentially
            let finalResult = {
                reply: "",
                summary: null,
                tasks: [],
                emailDraft: null,
                workflowExecuted: intents
            };

            for (const step of executionPlan) {
                console.log(`⚙️ Executing Step ${step.step}: ${step.action}`);

                switch (step.action) {
                    case 'summarize_document':
                        if (documentText || command.length > 100) {
                            const textToSummarize = documentText || command;
                            finalResult.summary = await novaService.summarizeDocument(textToSummarize);
                            finalResult.reply += `\n\n📄 **Summary:**\n${finalResult.summary}`;
                        } else {
                            finalResult.reply += "\n\n⚠️ No document content found to summarize.";
                        }
                        break;

                    case 'generate_tasks':
                        const textForTasks = documentText || command;
                        const extractedTasks = await novaService.generateTasks(textForTasks);

                        // Save each task to MongoDB
                        for (const t of extractedTasks) {
                            const savedTask = await Task.create({
                                title: t.title,
                                description: t.description || "Generated by AI Copilot",
                                status: 'pending'
                            });
                            finalResult.tasks.push(savedTask);
                        }
                        finalResult.reply += `\n\n✅ Created ${finalResult.tasks.length} new tasks in your pipeline.`;
                        break;

                    case 'draft_email':
                        const draftPrompt = `Draft a professional email based on this context: ${documentText || command}`;
                        finalResult.emailDraft = await novaService.generateResponse(draftPrompt);
                        finalResult.reply += `\n\n📧 **Email Draft:**\n${finalResult.emailDraft}`;
                        break;

                    case 'plan_schedule':
                        const schedulePrompt = `Create a structured schedule based on this: ${command}`;
                        const schedule = await novaService.generateResponse(schedulePrompt);
                        finalResult.reply += `\n\n📅 **Planned Schedule:**\n${schedule}`;
                        break;

                    default:
                        if (intents.length === 1) {
                            finalResult.reply = await novaService.generateResponse(command);
                        }
                }
            }

            // Step 5: Combine & Return Results
            console.log("🏁 Workflow Completed Successfully.\n");
            return finalResult;

        } catch (error) {
            console.error("❌ Agent Workflow Error:", error);
            throw error;
        }
    }
}

module.exports = new WorkflowService();
